### ISSUE TITLE
Can't push to Heroku: Has-Bit-Field accesses DB during asset pre-compile

### ISSUE THREAD

**Issue by jfeldstein** [pjb3/has-bit-field#19]
Can't push to heroku, because the build fails during asset precompile. 

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       could not connect to server: Connection refused
       Is the server running on host "127.0.0.1" and accepting
       TCP/IP connections on port 5432?
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `initialize'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `new'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `connect'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:548:in `initialize'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:440:in `new_connection'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `checkout_new_connection'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `acquire_connection'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:356:in `block in checkout'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in `checkout'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:546:in `retrieve_connection'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_handling.rb:79:in `retrieve_connection'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_handling.rb:53:in `connection'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/model_schema.rb:203:in `table_exists?'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/has-bit-field-2.0.0/lib/has-bit-field.rb:7:in `has_bit_field'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/app/models/user.rb:35:in `<class:User>'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/app/models/user.rb:1:in `<top (required)>'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:330:in `require_or_load'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:463:in `load_missing_constant'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:184:in `const_missing'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/inflector/methods.rb:226:in `const_get'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/inflector/methods.rb:226:in `block in constantize'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/inflector/methods.rb:224:in `each'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/inflector/methods.rb:224:in `inject'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/inflector/methods.rb:224:in `constantize'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:535:in `get'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:566:in `constantize'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/devise-3.2.3/lib/devise.rb:297:in `get'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/devise-3.2.3/lib/devise/mapping.rb:77:in `to'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/devise-3.2.3/lib/devise/mapping.rb:72:in `modules'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/devise-3.2.3/lib/devise/mapping.rb:89:in `routes'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/devise-3.2.3/lib/devise/mapping.rb:156:in `default_used_route'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/devise-3.2.3/lib/devise/mapping.rb:66:in `initialize'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/devise-3.2.3/lib/devise.rb:331:in `new'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/devise-3.2.3/lib/devise.rb:331:in `add_mapping'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/devise-3.2.3/lib/devise/rails/routes.rb:221:in `block in devise_for'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/devise-3.2.3/lib/devise/rails/routes.rb:220:in `each'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/devise-3.2.3/lib/devise/rails/routes.rb:220:in `devise_for'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/config/routes.rb:4:in `block in <top (required)>'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:341:in `instance_exec'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:341:in `eval_block'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:319:in `draw'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/config/routes.rb:1:in `<top (required)>'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `each'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/file_update_checker.rb:75:in `call'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/file_update_checker.rb:75:in `execute'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:27:in `updater'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:6:in `execute_if_updated'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `run'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application.rb:215:in `initialize!'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/config/environment.rb:5:in `<top (required)>'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application.rb:189:in `require_environment!'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application.rb:250:in `block in run_tasks_blocks'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:54:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !

 !     Push rejected, failed to compile Ruby app
```

Posting here (and not in devise) because of lines: 

```
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/model_schema.rb:203:in `table_exists?'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/vendor/bundle/ruby/2.0.0/gems/has-bit-field-2.0.0/lib/has-bit-field.rb:7:in `has_bit_field'
       /tmp/build_b7fe6c0b-0022-4acc-b025-9472a92a777c/app/models/user.rb:35:in `<class:User>'
```

I've already tried enabling the [user-env](http://stackoverflow.com/a/16434976/311901) lab.

**Comment by jfeldstein** [comment]
Oh, by the way, the database field was missing. Weird error. 

I fixed by removing the Has-Bit-Field definition from my model for now.
